M48
; DRILL file {KiCad 7.0.8} date Sun Dec  3 14:11:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-03T14:11:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0276
%
G90
G05
T1
X5.2965Y-2.9177
X5.2965Y-3.1453
T2
X5.3976Y-2.6772
X5.3976Y-3.3858
X5.4685Y-2.6772
X5.4685Y-3.3858
T0
M30
